server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: subject
  application:
    name: lab-5-subject
words: I,You,He,She,It

---
spring:
  profiles: verb
  application:
    name: lab-5-verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
  application:
    name: lab-5-article
words: a,the

---
spring:
  profiles: adjective
  application:
    name: lab-5-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
  application:
    name: lab-5-noun
words: boat,book,vote,seat,backpack,partition,groundhog
