spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/patrykkrawczyk/udemy-Microservices-with-Spring-Cloud
          search-paths: ConfigData/lab5
server:
  port: 8001
