eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  # Allow Eureka to recognize two apps of the same type on the same host as separate instances:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  profiles: subject
  application:
    name: lab-8-subject
words: I,You,He,She,It

---
spring:
  profiles: verb
  application:
    name: lab-8-verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
  application:
    name: lab-8-article
words: a,the

---
spring:
  profiles: adjective
  application:
    name: lab-8-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
  application:
    name: lab-8-noun
words: boat,book,vote,seat,backpack,partition,groundhog
